# Site settings
title: Farmhouse Saison and Wild Ale Festival
email: info@farmhousefest.com
description: > 
  Farmhouse Fest is a unique saison and wild ale festival. June 18th 2016, Vancouver, BC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://farmhousefest.com" # the base hostname & protocol for your site
twitter_username: farmhousefest
instagram_username: farmhousefest
facebook_username: FarmhouseFest
ticket_link: https://farmhousefest2016.eventbrite.ca/

# Build settings
markdown: kramdown
